version: '3'

services:
  app1:
    build:
      context: ./ollama
    container_name: app1
    ports:
      - "11434:11434"
    networks:
      - my-network

  app2:
    build:
      context: ./n8n
    container_name: app2
    ports:
      - "5678:5678"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
