services:
  app1:
    build:
      context: ./ollama
    container_name: app1
    ports:
      - "11434:11434"
    networks:
      - my-network

  app2:
    build:
      context: ./n8n
    container_name: app2
    ports:
      - "5678:5678"
    networks:
      - my-network
    environment:
      - N8N_VERSION=0.211.1  # Asegúrate de especificar una versión válida de n8n
      - NODE_ENV=production
      - N8N_RELEASE_TYPE=stable
    command: ["n8n", "start"]

networks:
  my-network:
    driver: bridge