services:
  # Servicio n8n
  - type: web
    name: deployagent
    env: docker
    region: frankfurt
    plan: standard
    branch: main
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: NODE_ENV
        value: production
      - key: N8N_LOG_LEVEL
        value: verbose
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_METRICS_ENABLED
        value: false
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: N8N_ENCRYPTION_KEY
        value: "your-secret-key-min-32-chars-long"
      - key: OLLAMA_ORIGINS
        value: "*"
      - key: OLLAMA_HOST
        value: 127.0.0.1
    dockerfilePath: ./Dockerfile
    buildCommand: |
      docker build \
        --build-arg N8N_VERSION=1.76.3 \
        -t n8n-ollama .
    startCommand: |
      /usr/local/bin/ollama serve &
      sleep 5
      su-exec node /usr/local/bin/n8n start --port $PORT
    numInstances: 1
    disk:
      name: data
      mountPath: /home/node/.n8n
      sizeGB: 10
