services:
  # Servicio n8n
  - type: web
    name: deployagent
    env: docker
    region: frankfurt
    plan: standard
    branch: main
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: NODE_ENV
        value: production
      - key: N8N_LOG_LEVEL
        value: verbose
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_METRICS_ENABLED
        value: false
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: N8N_ENCRYPTION_KEY
        value: "dK8xJ2mP9nQ7vR4tL5wC3bE6yH8uM1pX"
      - key: OLLAMA_ORIGINS
        value: "*"
      - key: OLLAMA_HOST
        value: 127.0.0.1
    dockerfilePath: Dockerfile
    startCommand: /docker-entrypoint.sh
    numInstances: 1
