# Configuración de Render.com
services:
  - type: web
    name: deployagent
    env: docker
    region: frankfurt
    plan: starter-plus
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: /docker-entrypoint.sh
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: "true"
      # Variables críticas N8N
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_DISABLE_TUNNEL
        value: "true"
      - key: N8N_METRICS_DISABLED
        value: "true"
      - key: N8N_DIAGNOSTICS_DISABLED
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        value: "dK8xJ2mP9nQ7vR4tL5wC3bE6yH8uM1pX"  # Cambiar en producción
      - key: NODE_ENV
        value: "production"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "3000"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_USER_FOLDER
        value: "/home/node/.n8n"
      - key: N8N_LOG_LEVEL
        value: "verbose"
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION
        value: "true"
      # Ollama
      - key: OLLAMA_HOST
        value: "127.0.0.1"
      - key: OLLAMA_ORIGINS
        value: "https://${RENDER_EXTERNAL_URL}"
      - key: OLLAMA_SKIP_GPU_DETECTION
        value: "true"
      - key: OLLAMA_CPU_ONLY
        value: "true"
      - key: OLLAMA_MODELS
        value: "llama3.2:1b"
