version: '3.8'

services:
  n8n-ollama:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
      - N8N_PORT=3000
      - N8N_PROTOCOL=http
      - N8N_DISABLE_TUNNEL=true
      - N8N_METRICS_DISABLED=true
      - N8N_DIAGNOSTICS_DISABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_SKIP_WEBHOOK_DEREGISTRATION=true
      - N8N_LOG_LEVEL=verbose
      - OLLAMA_HOST=127.0.0.1
      - OLLAMA_SKIP_GPU_DETECTION=true
      - OLLAMA_CPU_ONLY=true
      - OLLAMA_MODELS=llama3.2:1b
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./data/ollama:/root/.ollama
    restart: unless-stopped
